### PR TITLE
patch1

### PR DESCRIPTION
**Pull request by gwelican**

### CODE REVIEW

**Comment by etheld** [comment]
c

**Comment by etheld** [comment]
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [MazeMain.java#L14](https://github.com/etheld/maze/blob/3882ac07065f070b426fa03df576768b741d3912/src/main/java/uk/gov/dwp/maze/MazeMain.java#L14): Add a private constructor to hide the implicit public one. [rule](http://sonarqube.gwelican.eu/coding_rules#rule_key=squid%3AS1118)
1. ![MAJOR][MAJOR] [MazeMain.java#L27](https://github.com/etheld/maze/blob/3882ac07065f070b426fa03df576768b741d3912/src/main/java/uk/gov/dwp/maze/MazeMain.java#L27): Replace this usage of System.out or System.err by a logger. [rule](http://sonarqube.gwelican.eu/coding_rules#rule_key=squid%3AS106)

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'

**Comment by etheld** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [MazeMain.java#L16](https://github.com/etheld/maze/blob/ad6fc12f64a8a6594d462e9a3677c243e96c50c6/src/main/java/uk/gov/dwp/maze/MazeMain.java#L16): Method uk.gov.dwp.maze.MazeMain.<static initializer for MazeMain>() specifies an unrelated class when allocating a Logger.  Saw "uk.gov.dwp.maze.Explorer", expected "uk.gov.dwp.maze.MazeMain". [rule](http://sonarqube.gwelican.eu/coding_rules#rule_key=fb-contrib%3ALO_SUSPECT_LOG_CLASS)

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'

**Comment by etheld** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [MazeMain.java#L16](https://github.com/etheld/maze/blob/27bdf551ed5592ad4396c544ac872486733cfcbd/src/main/java/uk/gov/dwp/maze/MazeMain.java#L16): Method uk.gov.dwp.maze.MazeMain.<static initializer for MazeMain>() specifies an unrelated class when allocating a Logger.  Saw "uk.gov.dwp.maze.Explorer", expected "uk.gov.dwp.maze.MazeMain". [rule](http://sonarqube.gwelican.eu/coding_rules#rule_key=fb-contrib%3ALO_SUSPECT_LOG_CLASS)

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'

**Comment by etheld** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [MazeMain.java#L16](https://github.com/etheld/maze/blob/43d4c7a682ca3ab93ef4e6cd4edbd8c20969bc22/src/main/java/uk/gov/dwp/maze/MazeMain.java#L16): Method uk.gov.dwp.maze.MazeMain.<static initializer for MazeMain>() specifies an unrelated class when allocating a Logger.  Saw "uk.gov.dwp.maze.Explorer", expected "uk.gov.dwp.maze.MazeMain". [rule](http://sonarqube.gwelican.eu/coding_rules#rule_key=fb-contrib%3ALO_SUSPECT_LOG_CLASS)

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'

**Comment by etheld** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [MazeMain.java#L16](https://github.com/etheld/maze/blob/d862f8c4c3c539cb5f85ce5e273c48bfaf615c05/src/main/java/uk/gov/dwp/maze/MazeMain.java#L16): Method uk.gov.dwp.maze.MazeMain.<static initializer for MazeMain>() specifies an unrelated class when allocating a Logger.  Saw "uk.gov.dwp.maze.Explorer", expected "uk.gov.dwp.maze.MazeMain". [rule](http://sonarqube.gwelican.eu/coding_rules#rule_key=fb-contrib%3ALO_SUSPECT_LOG_CLASS)

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'

**Comment by etheld** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [MazeMain.java#L16](https://github.com/etheld/maze/blob/06f5f727f850e3f9cbffda19d05b53694973f6e5/src/main/java/uk/gov/dwp/maze/MazeMain.java#L16): Method uk.gov.dwp.maze.MazeMain.<static initializer for MazeMain>() specifies an unrelated class when allocating a Logger.  Saw "uk.gov.dwp.maze.Explorer", expected "uk.gov.dwp.maze.MazeMain". [rule](http://sonarqube.gwelican.eu/coding_rules#rule_key=fb-contrib%3ALO_SUSPECT_LOG_CLASS)

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'

**Comment by gwelican** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [MazeMain.java#L16](https://github.com/etheld/maze/blob/47c27f24a83f70243134da518b194c2db5e31d98/src/main/java/uk/gov/dwp/maze/MazeMain.java#L16): Method uk.gov.dwp.maze.MazeMain.<static initializer for MazeMain>() specifies an unrelated class when allocating a Logger.  Saw "uk.gov.dwp.maze.Explorer", expected "uk.gov.dwp.maze.MazeMain". [rule](http://sonarqube.gwelican.eu/coding_rules#rule_key=fb-contrib%3ALO_SUSPECT_LOG_CLASS)

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'

**Pull request closed without merging**
